context:
  version: 0.14.0

package:
  name: xeus-python
  version: '{{ version }}'

source:
  url: https://github.com/jupyter-xeus/xeus-python/archive/refs/tags/{{ version }}.tar.gz
  sha256: fe92c696ca25bc144025cd05b78c9069bd400cc2477a1d240adfa24ed828b451

build:
  number: 0

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - cmake
    - ninja
  host:
    - python
    - nlohmann_json
    - xeus
    - pybind11
    - pybind11_json
    - xtl
    - pyjs >=0.6.1
  run:
    - python
    - ipython
    - jedi
    - xeus-python-shell >=0.4.1,<0.5
    - wasm_requests >=0.1.5

test:
  commands:
    - sel(emscripten): test -f $PREFIX/bin/xpython_wasm.wasm
    - sel(emscripten): test -f $PREFIX/bin/xpython_wasm.js

about:
  home: https://github.com/jupyter-xeus/xeus-python
  license: BSD-3
  license_family: BSD-3
  license_file: LICENSE
  summary: xeus-python
  doc_url: https://github.com/jupyter-xeus/xeus-python
  dev_url: https://github.com/jupyter-xeus/xeus-python

extra:
  recipe-maintainers:
    - DerThorsten
    - martinRenou
