context:
  version: "7.4.1"

package:
  name: pytest
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/p/pytest/pytest-{{ version }}.tar.gz
  sha256: 2f2301e797521b23e4d2585a0a3d7b5e50fdddaaf7e7d6773ea26ddb17c213ab

build:
  number: 0

requirements:
  build:
    - python
    - cross-python_emscripten-32
    - pip
  host:
    - python
  run:
    - atomicwrites
    - attrs
    - more-itertools
    - pluggy
    - py
    - six
    - iniconfig

about:
  home: https://docs.pytest.org/en/latest/
  license: MIT
  license_file: LICENSE
  summary: Simple and powerful testing with Python.
  description: |
    The pytest framework makes it easy to write small tests, yet scales to
    support complex functional testing for applications and libraries.
  doc_url: https://docs.pytest.org/en/latest/
  dev_url: https://github.com/pytest-dev/pytest/

extra:
  recipe-maintainers:
    - DerThorsten
