context:
  version: "0.7.25"

package:
  name: libsolv
  version: "{{ version }}"

source:
  - url: https://github.com/openSUSE/libsolv/archive/{{ version }}.tar.gz
    sha256: b382bba4196b19c36eb34e0ef02546c0b922be601c6f73390c9ab643895b656a
    patches:
      - conda_variant_priorization.patch
  - path: CMakeLists.txt
  - path: tools/CMakeLists.txt
    folder: tools

build:
  number: 0

requirements:
  build:
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - make
    - ninja
    - cmake
  host:
    - zlib
