packages:
  python-dateutil:
    include_patterns:
      - pattern: '*.so'
      - pattern: '*.py'
      - pattern: '*.json'
      - pattern: '*dateutil-zoneinfo.tar.gz'
    exclude_patterns:
      - pattern: '**/tests/**/*.py'
      - pattern: '**/tests/**/*.so'
  # For matplotlib <3.5.2 which didn't have matplotlib-base published
  matplotlib:
    include_patterns:
      - pattern: '*.so'
      - pattern: '*.py'
      - pattern: '*.json'
      - pattern: '**/matplotlib/mpl-data/**'
    exclude_patterns:
      - pattern: '**/tests/**/*.py'
      - pattern: '**/tests/**/*.so'
  matplotlib-base:
    include_patterns:
      - pattern: '*.so'
      - pattern: '*.py'
      - pattern: '*.json'
      - pattern: '**/matplotlib/mpl-data/**'
    exclude_patterns:
      - pattern: '**/tests/**/*.py'
      - pattern: '**/tests/**/*.so'
  scikit-learn:
    include_patterns:
      - pattern: '*.so'
      - pattern: '*.py'
      - pattern: '*.json'
      - pattern: '**/sklearn/datasets/**'
    exclude_patterns:
      - pattern: '**/tests/**/*.py'
      - pattern: '**/tests/**/*.so'
  scikit-image:
    include_patterns:
      - pattern: '*.so'
      - pattern: '*.py'
      - pattern: '*.json'
      - pattern: '**/skimage/data/**'
      - pattern: '**/skimage/io/_plugins/*.ini'

    exclude_patterns:
      - pattern: '**/tests/**/*.py'
      - pattern: '**/tests/**/*.so'
default:
  include_patterns:
    - pattern: '*.so'
    - pattern: '*.py'
    - pattern: '*.json'
  exclude_patterns:
    - pattern: '**/tests/**/*.py'
    - pattern: '**/tests/**/*.so'
