context:
  version: 0.7.2

package:
  name: xeus-lua
  version: '{{ version }}'

source:
  url: https://github.com/jupyter-xeus/xeus-lua/archive/refs/tags/{{ version }}.tar.gz
  sha256: 8dff0e71e0d674fa8734db036c0499a85c7db953fd96eef239104245a3a47e54

build:
  number: 0

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - cmake
    - ninja
  host:
    - lua
    - nlohmann_json
    - xeus-lite
    - xtl >=0.7,<0.8
    - xcanvas >=0.4,<5.0

test:
  commands:
    - sel(emscripten): test -f $PREFIX/bin/xpython_wasm.wasm
    - sel(emscripten): test -f $PREFIX/bin/xpython_wasm.js

about:
  home: https://github.com/jupyter-xeus/xeus-python
  license: BSD-3
  license_family: BSD-3
  license_file: LICENSE
  summary: xeus-python
  doc_url: https://github.com/jupyter-xeus/xeus-python
  dev_url: https://github.com/jupyter-xeus/xeus-python

extra:
  recipe-maintainers:
    - DerThorsten
    - martinRenou
    - JohanMabille
