context:
  version: 17.0.1

package:
  name: llvm
  version: '{{ version }}'

source:
  url: https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-{{ version }}.tar.gz
  sha256: d51b10be66c10a6a81f4c594b554ffbf1063ffbadcb810af37d1f88d6e0b49dd

build:
  number: 0

requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ compiler("cxx") }}'
    - cmake
    - ninja

about:
  home: https://llvm.org
  license: Apache-2.0 WITH LLVM-exception
  license_family: Apache
  license_file: LICENSE.TXT
  summary: llvm
  doc_url: https://llvm.org/docs
  dev_url: https://github.com/llvm/llvm-project
