context:
  version: 0.3.0
  name: picomamba

package:
  name: '{{ name }}'
  version: '{{ version }}'

source:
  - url: https://github.com/mamba-org/picomamba/archive/refs/tags{{ version }}.tar.gz
    sha256: bb24c28e84d5c27f80dfe267362135c255e809f9ab79c0de69a4ca810741c1bf

build:
  number: 0

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - cmake
    - ninja
    - numpy
  host:
    - python
    - pybind11
    - numpy
    - libsolv
    - nlohmann_json
  run:
    - numpy
    - python


about:
  home: https://github.com/mamba-org/picomamba
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pyb2d
  doc_url: https://github.com/mamba-org/picomamba
  dev_url: https://github.com/mamba-org/picomamba

extra:
  recipe-maintainers:
    - DerThorsten

  emscripten_tests:
    python:
      pytest_files:
        - test_picomamba.py

