context:
  version: 2.11.0

package:
  name: pybind11
  version: '{{ version }}'

source:
  url: https://github.com/pybind/pybind11/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7af30a84c6810e721829c4646e31927af9d8861e085aa5dd37c3c8b8169fcda1
  patches:
    - sel(emscripten): patches/0001-no-bitsize-check.patch
build:
  number: 0

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - cmake
    - ninja
  host:
    - python


features:
  - name: env_node
    default: false
  - name: env_web
    default: true



about:
  home: https://github.com/pybind/pybind11
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Seamless operability between C++11 and Python
  doc_url: https://pybind11.readthedocs.io/

extra:
  recipe-maintainers:
    - DerThorsten

