context:
  version: 3.4.1

package:
  name: eigen
  version: '{{ version }}'

source:
  url: https://gitlab.com/libeigen/eigen/-/archive/{{ version }}/eigen-{{ version }}.tar.gz
  sha256: 99566d127ec338e085a0b26c6fc25f766ad7fdf444cf62a242072f8f85c4a242

build:
  number: 0

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - cmake
    - ninja

test:
  commands:
    - sel(emscripten): test -d ${PREFIX}/include/eigen3

about:
  home: http://eigen.tuxfamily.org/
  license: MPL-2.0
  license_file: COPYING.MPL2
  summary: eigen
  doc_url: http://eigen.tuxfamily.org/
  dev_url: https://gitlab.com/libeigen/eigen.git

extra:
  recipe-maintainers:
    - traversaro
