context:
  version: 0.16.0
  name: pyjs
package:
  name: '{{name}}'
  version: '{{ version }}'
  
source:
  url: https://github.com/emscripten-forge/{{name}}/archive/refs/tags/{{version}}.tar.gz
  sha256: 6ee80718b24e47636a7fe917507cb328825bb3d89bec4f6cc6a19a4af53b275a

build:
  number: 0

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - cmake
    - ninja
  host:
    - python
    - sqlite
    - zlib
    - bzip2
    - libffi
    - pybind11

about:
  home: https://github.com/emscripten-forge/pyjs
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: pyjs


extra:
  recipe-maintainers:
    - DerThorsten

