context:
  version: 1.2.0
  name: pyjs
package:
  name: '{{name}}'
  version: '{{ version }}'

source:
  - url: https://github.com/emscripten-forge/{{name}}/archive/refs/tags/{{version}}.tar.gz
    sha256: 21211596df09778de7ebfc34267b6759da5ef5bfb0ce7c8436b098e9bc83b2f3
build:
  number: 0

requirements:
  build:
    - '{{ compiler("cxx") }}'
    - cmake
    - ninja
    - python
  host:
    - python
    - sqlite
    - zlib
    - bzip2
    - libffi
    - pybind11

about:
  home: https://github.com/emscripten-forge/pyjs
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: pyjs


extra:
  recipe-maintainers:
    - DerThorsten
